### ISSUE TITLE
how to watch a cv::mat  value

### ISSUE THREAD

**Issue by xifen523** [Mohamed5341/opencv-image#1]
This plugin of yours is very useful for c++ debugging opencv. In the future could you add a function that shows the value of cv::mat

**Comment by Mohamed5341** [comment]
Thank you for using it, but could you be more specific about your request as c++ debugging extension shows `cv::Mat` variable, it's member variables and their values, or do you mean display the whole matrix data columns and rows.

**Comment by xifen523** [comment]
Sometimes cv::Mat is used to save matrix data, but when debugging, the exact values are not visible, which is very detrimental to debugging.
```
cv::Mat<int> q(cv::Size(tracks_.size(), _detections.size()), int(0));
```
![image](https://github.com/Mohamed5341/opencv-image/assets/57985338/ba78d0a8-eafb-4417-942a-98e7c05a71db)
You can only see these in vscode's watch, there are no specific values for the matrix.

It would be very easy to debug this matrix if I could see the values in the specific cv::mat

**Comment by Mohamed5341** [comment]
Ok, I see what you mean. Soon this will be added to extension.

**Comment by Mohamed5341** [comment]
Added display matrix as table  ([ecf0f85](https://github.com/Mohamed5341/opencv-image/commit/ecf0f85fec3e0d56b36dee9259cfcc162f139d8d)), I hope this is what you asked for. Please, tell me your opinion about it. 

Sorry about extension delay, it will be fixed as soon as possible.

**Comment by xifen523** [comment]
Thank you very much for getting this feature developed.

When using it, I found that 'Show Image Matrix' would report an error if the image stored in 'mat' was not an image.

![image](https://github.com/Mohamed5341/opencv-image/assets/57985338/751a4357-d6c8-47cb-b7cf-db3f69629471)

I actually defined the matrix as follows:

```
cv::Mat assigmentsBin = cv::Mat::zeros(cv::Size(deteSize, prevDetSize), CV_32SC1);
cv::Mat costMat = cv::Mat(cv::Size(deteSize, prevDetSize), CV_32FC1);
```
![image](https://github.com/Mohamed5341/opencv-image/assets/57985338/1c314e77-8026-4acf-8f4b-004e6ff995c0)


How to solve this situation
